AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - fetching.gemspec
    - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
