require: rubocop-rspec

AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - fetching.gemspec

Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 100

RegexpLiteral:
  MaxSlashes: 0
  Exclude:
    - Guardfile

TrailingComma:
  EnforcedStyleForMultiline: comma
