AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - fetching.gemspec
    - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 100

<<<<<<< HEAD
Style/RegexpLiteral:
=======
RegexpLiteral:
>>>>>>> Update rubocop syntax for new version
  Exclude:
    - Guardfile

Style/TrailingCommaInLiteral:
<<<<<<< HEAD
=======
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
>>>>>>> Update rubocop syntax for new version
  EnforcedStyleForMultiline: comma
