require: rubocop-rspec

AllCops:
  Include:
    - Gemfile
    - Rakefile

Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

SpecialGlobalVars:
  Exclude:
    - fetching.gemspec

TrailingComma:
  EnforcedStyleForMultiline: comma
